### ISSUE TITLE
Exception "Null check operator used on a null value" when running in Flutter package

### ISSUE THREAD

**Issue by relf108** [noojee/pub_release#8]
**ANDROID_HOME:**
`/usr/lib/android-sdk`
**pub_release -v output:**
```
_pathToScript: /usr/lib/dart/bin/dart
dart 7.1.11
exists: true /home/tsutton/Projects/dimension_ratios/pubspec.yaml followLinks: true
read: /home/tsutton/Projects/dimension_ratios/pubspec.yaml, delim: 

exists: true /home/tsutton/Projects/dimension_ratios/pubspec.yaml followLinks: true

Found dimension_ratios version 0.0.1

ask:  Is this the correct package? (y/n): toLower: true hidden: false required: false defaultValue: null
Is this the correct package? (y/n): y
ask: pre validation "y"
ask: post validation "y"
ask: result y

exists: true /home/tsutton/Projects/dimension_ratios/pubspec.yaml followLinks: true
exists: true /home/tsutton/Projects/dimension_ratios/pubspec.lock followLinks: true
exists: true /home/tsutton/Projects/dimension_ratios/.dart_tool/package_config.json followLinks: true
env:  PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/dart/bin:/home/tsutton/.pub-cache/bin:/home/tsutton/flutter/bin:/usr/lib/dart/bin:/usr/lib/android-sdk/cmdline-tools/latest/bin:/home/tsutton/.pub-cache/bin:/home/tsutton/flutter/bin:/usr/lib/dart/bin:/usr/lib/android-sdk/cmdline-tools/latest/bin
exists: false /usr/local/sbin/critical_test followLinks: true
exists: false /usr/local/bin/critical_test followLinks: true
exists: false /usr/sbin/critical_test followLinks: true
exists: false /usr/bin/critical_test followLinks: true
exists: false /sbin/critical_test followLinks: true
exists: false /bin/critical_test followLinks: true
exists: false /usr/games/critical_test followLinks: true
exists: false /usr/local/games/critical_test followLinks: true
exists: false /snap/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /home/tsutton/.pub-cache/bin/critical_test followLinks: true
exists: false /home/tsutton/flutter/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /usr/lib/android-sdk/cmdline-tools/latest/bin/critical_test followLinks: true
exists: false /home/tsutton/.pub-cache/bin/critical_test followLinks: true
exists: false /home/tsutton/flutter/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /usr/lib/android-sdk/cmdline-tools/latest/bin/critical_test followLinks: true
exists: true /home/tsutton/Projects/dimension_ratios/.gitignore followLinks: true
read: /home/tsutton/Projects/dimension_ratios/.gitignore, delim: 

exists: true /home/tsutton/Projects/dimension_ratios/.gitignore followLinks: true
exists: true /home/tsutton/Projects/dimension_ratios/test followLinks: true
env:  PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/dart/bin:/home/tsutton/.pub-cache/bin:/home/tsutton/flutter/bin:/usr/lib/dart/bin:/usr/lib/android-sdk/cmdline-tools/latest/bin:/home/tsutton/.pub-cache/bin:/home/tsutton/flutter/bin:/usr/lib/dart/bin:/usr/lib/android-sdk/cmdline-tools/latest/bin
exists: false /usr/local/sbin/critical_test followLinks: true
exists: false /usr/local/bin/critical_test followLinks: true
exists: false /usr/sbin/critical_test followLinks: true
exists: false /usr/bin/critical_test followLinks: true
exists: false /sbin/critical_test followLinks: true
exists: false /bin/critical_test followLinks: true
exists: false /usr/games/critical_test followLinks: true
exists: false /usr/local/games/critical_test followLinks: true
exists: false /snap/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /home/tsutton/.pub-cache/bin/critical_test followLinks: true
exists: false /home/tsutton/flutter/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /usr/lib/android-sdk/cmdline-tools/latest/bin/critical_test followLinks: true
exists: false /home/tsutton/.pub-cache/bin/critical_test followLinks: true
exists: false /home/tsutton/flutter/bin/critical_test followLinks: true
exists: false /usr/lib/dart/bin/critical_test followLinks: true
exists: false /usr/lib/android-sdk/cmdline-tools/latest/bin/critical_test followLinks: true
Unhandled exception:
Null check operator used on a null value
#0      exeName (package:pub_release/src/release_runner.dart:437:29)
#1      ReleaseRunner.doRunTests (package:pub_release/src/release_runner.dart:410:11)
#2      ReleaseRunner.pubRelease.<anonymous closure> (package:pub_release/src/release_runner.dart:44:18)
#3      ReleaseRunner.doRun (package:pub_release/src/release_runner.dart:390:17)
#4      ReleaseRunner.pubRelease (package:pub_release/src/release_runner.dart:36:5)
#5      main (file:///home/tsutton/.pub-cache/hosted/pub.dartlang.org/pub_release-7.1.11/bin/pub_release.dart:152:14)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Flutter doctor -v output:**
```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.105, on Pop!_OS 21.04 5.12.18-xanmod3, locale en_AU.UTF-8)
    • Flutter version 2.4.0-5.0.pre.105 at /home/tsutton/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a5b9b5774a (2 days ago), 2021-07-19 20:23:45 -0700
    • Engine revision 9edde7423f
    • Dart version 2.14.0 (build 2.14.0-332.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /usr/lib/android-sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /usr/lib/android-sdk
    • Java binary at: /home/tsutton/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.1-1~kisak~h
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/tsutton/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Pop!_OS 21.04 5.12.18-xanmod3

! Doctor found issues in 1 category.
```

**Comment by bsutton** [comment]
Fixed in 7.1.14.
